name: video_editor
version: 1.4.2
description: A video editor that allows to trim, crop, rotate and scale video with a very flexible UI Design.
homepage: https://github.com/seel-channel/video_editor

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  ffmpeg_kit_min_gpl_unify: ^6.0.3-LTS
  path_provider: ^2.1.5
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6
  path: ^1.9.1 # update to `1.8.1` causes #79

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4